name: MasterStoryteller
favicon: null
layout_spectrum: 0.033355894731357694
typography_spectrum: 0.6490433998405933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
